version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - verdemuse-network

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    env_file:
      - .env
    command: streamlit run src/presentation/streamlit/app.py
    depends_on:
      - api
    networks:
      - verdemuse-network

networks:
  verdemuse-network:
    driver: bridge